"""TBHarness: owns the Thunderbird process and the Marionette session.

The driver launches Thunderbird itself (rather than attaching to a separately
launched process) because Marionette.quit()/restart() raise unless the instance
was launched by Marionette. restart(in_app=True) performs a graceful
nsIAppStartup.quit(eRestart) -- the same path a real user's restart takes, and
the only one that exercises the clean-shutdown phase where a temp add-on's
clearOnUninstall fires. A kill-and-relaunch would skip exactly the phase the
persistence test is trying to prove.

The cost -- no real-time console tee -- is recovered by tail_log().
"""

import os
import shutil
import socket
import subprocess
import sys
import time
from pathlib import Path

from marionette_driver.marionette import Marionette
from marionette_driver.addons import Addons
from mozprofile import Profile

import config


class HarnessError(RuntimeError):
    """Raised for harness setup/teardown problems (not test assertions)."""


def _guard_profile_path(path):
    """Refuse to delete anything that isn't clearly our throwaway profile.

    Two independent conditions must hold. The user's real Thunderbird profiles
    must never be at risk from a typo or an env var.
    """
    resolved = Path(path).resolve()
    lowered = str(resolved).lower().replace("/", "\\")

    if "appdata\\roaming\\thunderbird\\profiles" in lowered:
        raise HarnessError(
            "Refusing to touch {} -- that is inside the real Thunderbird "
            "profiles directory.".format(resolved)
        )

    if config.PROFILE_GUARD_TOKEN not in lowered:
        raise HarnessError(
            "Refusing to delete {} -- the path does not contain {!r}, so it "
            "does not look like the harness profile.".format(
                resolved, config.PROFILE_GUARD_TOKEN
            )
        )

    return resolved


def _port_is_open(port, host="127.0.0.1", timeout=0.5):
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.settimeout(timeout)
        return sock.connect_ex((host, port)) == 0


def _js_literal(value):
    """Render a Python value as a JS literal for user_pref()."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return '"{}"'.format(escaped)


def _still_running(pid):
    if not pid:
        return False
    try:
        out = subprocess.run(
            ["tasklist", "/FI", "PID eq {}".format(pid)],
            capture_output=True, text=True, timeout=15,
        )
        return str(pid) in (out.stdout or "")
    except Exception:
        return False


class TBHarness:
    def __init__(self, profile_dir=None, reset_profile=True, headless=False,
                 startup_timeout=180):
        self.profile_dir = Path(profile_dir) if profile_dir else config.PROFILE_DIR
        # HARNESS_KEEP_PROFILE=1 reuses the profile built by
        # run_setup_profile.py, so Ollama does not have to be reconfigured on
        # every launch. It can only ever *preserve* a profile, never wipe one.
        if os.environ.get("HARNESS_KEEP_PROFILE") == "1":
            reset_profile = False
        self.reset_profile = reset_profile
        self.headless = headless
        self.startup_timeout = startup_timeout
        self.marionette = None
        self.tb_bin = config.resolve_tb_bin()
        config.ensure_dirs()

    # -- profile --------------------------------------------------------------

    def _make_profile(self):
        if self.reset_profile and self.profile_dir.exists():
            target = _guard_profile_path(self.profile_dir)
            shutil.rmtree(target, ignore_errors=True)

        self.profile_dir.mkdir(parents=True, exist_ok=True)
        # Local Folders account referenced by the seeded prefs.
        (self.profile_dir / "Mail" / "Local Folders").mkdir(parents=True, exist_ok=True)
        self._write_user_js()
        return self.profile_dir

    def _write_user_js(self):
        """Write user.js, which is re-applied on every startup.

        prefs.js gets rewritten by Gecko; user.js does not, so the pref set
        survives the in-app restart intact.
        """
        lines = ["// Generated by tools/debug/tb_harness.py -- do not edit by hand."]
        for key, value in sorted(config.PREFS.items()):
            lines.append('user_pref("{}", {});'.format(key, _js_literal(value)))
        (self.profile_dir / "user.js").write_text(
            "\n".join(lines) + "\n", encoding="utf-8"
        )

    # -- lifecycle ------------------------------------------------------------

    def start(self):
        if _port_is_open(config.MARIONETTE_PORT):
            raise HarnessError(
                "Port {port} is already listening. Another Marionette-enabled "
                "Thunderbird (or a zombie from a previous run) is holding it.\n"
                "Close it, or run: taskkill /IM thunderbird.exe /F".format(
                    port=config.MARIONETTE_PORT
                )
            )

        self._make_profile()

        # GeckoInstance takes no env= parameter: _get_runner_args() builds the
        # child environment from os.environ.copy(), so these must be set on our
        # own process before Marionette is constructed.
        #
        # The SAFE_MODE pair matters because a hard kill can otherwise trip the
        # Safe Mode prompt and block every subsequent launch.
        os.environ["MOZ_DISABLE_AUTO_SAFE_MODE"] = "1"
        os.environ["MOZ_DISABLE_SAFE_MODE_KEY"] = "1"
        os.environ.pop("MOZ_APP_LAUNCHER", None)

        # -no-remote is essential: without it, launching while the user's normal
        # Thunderbird is running would hand off to that instance and drive the
        # REAL profile. (GeckoInstance appends -marionette itself.)
        app_args = ["-no-remote"]

        # A Profile OBJECT, not a path string. Given a path, mozprofile's
        # _update_profile() does Profile.clone() into a tempfile.mkdtemp() and
        # runs Thunderbird against the copy -- so prefs.js, the storage-sync
        # database and the account setup all land in the clone and are deleted at
        # shutdown. Nothing written at runtime would survive, which defeats
        # reset_profile=False entirely.
        #
        # restore=False keeps mozprofile from reverting our directory on cleanup.
        profile = Profile(profile=str(self.profile_dir), restore=False)

        self.marionette = Marionette(
            app="thunderbird",
            bin=str(self.tb_bin),
            profile=profile,
            # Passed in addition to user.js on purpose: ThunderbirdInstance's
            # own prefs fall back to {} (verified), and neither mechanism alone
            # is guaranteed to be applied.
            prefs=dict(config.PREFS),
            gecko_log=str(config.GECKO_LOG),
            app_args=app_args,
            headless=self.headless,
            port=config.MARIONETTE_PORT,
            startup_timeout=self.startup_timeout,
        )
        self.marionette.start_session()
        return self.marionette

    def install_addon(self, temp=True):
        """Install the add-on from the unpacked repo directory.

        No XPI build step -- this keeps CLAUDE.md's "no build tools" rule intact
        and means repo edits are picked up on the next run with zero packaging.
        """
        self._require_session()
        addons = Addons(self.marionette)
        return addons.install(path=str(config.REPO_ROOT), temp=temp)

    def restart(self):
        """Graceful in-app restart, preserving the profile."""
        self._require_session()
        # clean=False is critical: clean=True wipes the profile, which would
        # destroy the very state the persistence test is checking.
        self.marionette.restart(clean=False, in_app=True)
        return self.marionette

    def _current_pid(self):
        try:
            instance = getattr(self.marionette, "instance", None)
            runner = getattr(instance, "runner", None) if instance else None
            process = getattr(runner, "process_handler", None) if runner else None
            return getattr(process, "pid", None)
        except Exception:
            return None

    def stop(self, grace=10):
        if self.marionette is None:
            return

        pid = self._current_pid()

        try:
            self.marionette.quit(in_app=True)
        except Exception as exc:
            print("[harness] graceful quit failed: {}".format(exc), file=sys.stderr)

        try:
            self.marionette.cleanup()
        except Exception:
            pass

        # Make sure a crashed run can never leave a zombie holding the port.
        deadline = time.time() + grace
        while time.time() < deadline and _port_is_open(config.MARIONETTE_PORT):
            time.sleep(0.5)

        if _port_is_open(config.MARIONETTE_PORT) or _still_running(pid):
            self._force_kill(pid)

        self.marionette = None

    @staticmethod
    def _force_kill(pid):
        cmd = (["taskkill", "/PID", str(pid), "/T", "/F"] if pid
               else ["taskkill", "/IM", "thunderbird.exe", "/F"])
        print("[harness] force killing: {}".format(" ".join(cmd)), file=sys.stderr)
        try:
            subprocess.run(cmd, capture_output=True, timeout=30)
        except Exception as exc:
            print("[harness] taskkill failed: {}".format(exc), file=sys.stderr)

    # -- diagnostics ----------------------------------------------------------

    def tail_log(self, n=80):
        """Last n lines of the gecko log. Called automatically on failure."""
        path = config.GECKO_LOG
        if not path.exists():
            return "(no gecko log at {})".format(path)
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            return "(could not read {}: {})".format(path, exc)
        lines = text.splitlines()
        return "\n".join(lines[-n:]) if lines else "(gecko log is empty)"

    def print_log_tail(self, n=80):
        print("\n--- tail of {} ---".format(config.GECKO_LOG), file=sys.stderr)
        print(self.tail_log(n), file=sys.stderr)
        print("--- end of log tail ---\n", file=sys.stderr)

    def _require_session(self):
        if self.marionette is None:
            raise HarnessError("No Marionette session; call start() first.")

    # -- context manager ------------------------------------------------------

    def __enter__(self):
        self.start()
        return self

    def __exit__(self, exc_type, exc, tb):
        if exc_type is not None:
            self.print_log_tail()
        self.stop()
        return False
